export type FontFamily =
  | "Dancing Script"
  | "Roboto"
  | "Open Sans"
  | "Poppins"
  | "Montserrat"
  | "Oswald"
  | "Quicksand"
  | "Raleway"
  | "Source Sans Pro"
  | "Merriweather"
  | "Playfair Display"
  | "Roboto Condensed"
  | "Ubuntu"
  | "Arial"
  | "Georgia"
  | "Helvetica"
  | "Impact"
  | "Times New Roman"
  | "Courier New"
  | "Lucida Console"
  | "Verdana"
  | "Trebuchet MS"
  | "Brush Script MT"
  | "Baskerville"
  | "Calisto MT"
  | "Garamond"
  | "Century Gothic"
  | "Franklin Gothic"
  | "Rockwell"
  | "Cambria"
  | "Bodoni MT"
  | "Old English Text MT"
  | "Comic Sans MS"
  | "Jokerman"
  | "Kristen ITC"
  | "Papyrus"
  | "Curlz MT"
  | "Vivaldi"
  | "Chiller"
  | "Algerian"
  | "Bauhaus 93"
  | "Stencil"
  | "Wide Latin"
  | "Webdings"
  | "Wingdings"
  | "Zapf Dingbats"
  | "Mistral"
  | "Viner Hand ITC";
