#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Defineix el patró que permet missatges curts
SHORT_MESSAGE_PATTERN="release/"

# Obté el nom de la branca actual
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Llegeix el missatge de commit
while read line; do
    # Salta les línies que són comentaris
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi

    # Si la branca conté el patró, mostra un missatge i salta la validació
    if echo "$CURRENT_BRANCH" | grep -q "$SHORT_MESSAGE_PATTERN"; then
        echo -e "\033[0;33mSkipping length validation for branch: $CURRENT_BRANCH\033[0m"
        break
    fi

    # Comprova la longitud del missatge
    if [ ${#line} -ge 72 ] || [ ${#line} -le 10 ]; then
        echo -e "\033[0;31mThe length of the message has to be between 10 and 72 characters."
        exit 1
    fi
done < "${1}"

exit 0
