import { Languages } from "@/types/sequence";

// Noms natius dels idiomes disponibles per a la cerca de pictogrames d'ARASAAC
export const LANGUAGE_NAMES: Record<Languages, string> = {
  an: "Aragonés",
  ar: "العربية",
  bg: "Български",
  br: "Brezhoneg",
  ca: "Català",
  cs: "Čeština",
  da: "Dansk",
  de: "Deutsch",
  el: "Ελληνικά",
  en: "English",
  es: "Español",
  et: "Eesti",
  eu: "Euskara",
  fa: "فارسی",
  fr: "Français",
  gl: "Galego",
  he: "עברית",
  hr: "Hrvatski",
  hu: "Magyar",
  it: "Italiano",
  ko: "한국어",
  lt: "Lietuvių",
  lv: "Latviešu",
  mk: "Македонски",
  nb: "Norsk Bokmål",
  nl: "Nederlands",
  pl: "Polski",
  pt: "Português",
  ro: "Română",
  ru: "Русский",
  sk: "Slovenčina",
  sq: "Shqip",
  sv: "Svenska",
  sr: "Српски",
  val: "Valencià",
  uk: "Українська",
  zh: "中文",
};
